// This file is generated by scripts/generate-blog-manifest.mjs.
// Do not edit by hand; edit Markdown files in this directory instead.

export type BlogPostManifestEntry = {
  slug: string
  title: string
  description: string
  date: string
  tags: string[]
  contentHtml: string
}

// prettier-ignore
export const blogPosts: BlogPostManifestEntry[] = [
  {
    "slug": "hello-world",
    "title": "Hello, World",
    "description": "A first test post for the markdown-powered blog.",
    "date": "2026-07-20",
    "tags": [
      "portfolio",
      "notes"
    ],
    "contentHtml": "<h2>Why add a blog?</h2>\n<p>I wanted a small place to write down engineering notes, project decisions, and things I learn while building.</p>\n<p>This first version is intentionally simple:</p>\n<ul>\n<li>Write posts as Markdown files.</li>\n<li>Commit them with the rest of the site.</li>\n<li>Let the portfolio render them as static pages.</li>\n</ul>\n<p>That keeps publishing low-friction while leaving room to add a CMS later.</p>\n"
  }
]
